png("plot4.png",width=480,height=480)
a<- read.table(file = "household_power_consumption.txt",sep = ";", skip = 66637,nrows = 2880)
wDays <- strptime(paste(a$V1, a$V2), format='%d/%m/%Y %H:%M:%S')
par(mfrow=c(2,2))
plot(wDays, a$V3, type="l", xlab="", ylab="Global Active Power (kilowatts)")
plot(wDays, a$V5, type="l", xlab="datetime", ylab="Voltage")
plot(wDays, a$V7,type="l", xlab="", ylab="Energy sub metering")
lines(wDays,a$V8, col="red")
lines(wDays,a$V9, col="blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1), col=c("black","red","blue"),seg.len=1,bty="n")
plot(wDays, a$V4, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
